[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18" # Specify a Node.js version compatible with Next.js

[[plugins]]
  package = "@netlify/plugin-nextjs"
